"""reports/calibration.md — the two re-measured numbers, and what they mean.

    python -m futuresres.reporting.calibration_report

Combines the α-to-coverage mapping and the detection-floor sweep into one document, and
does the translation neither raw table does on its own: **the floor in basis points against
the cost floor**. That comparison is the whole point of re-measuring, because it decides
whether this project's binding constraint is the same one that closed the crypto catalog.

Reads the caches written by `futuresres.integrity.calibration`; computes nothing itself
beyond the arithmetic of combining them, so every number here traces to a measured run.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Final

import numpy as np

ROOT: Final[Path] = Path(__file__).resolve().parents[3]
REPORTS: Final[Path] = ROOT / "reports"
REPORT: Final[Path] = REPORTS / "calibration.md"

#: From reports/kurtosis.md — measured.
SIGMA_BPS: Final[dict[tuple[str, int], float]] = {
    ("MNQ", 1): 3.9, ("MNQ", 30): 21.4, ("MNQ", 60): 30.4, ("MNQ", 180): 52.2,
    ("MGC", 1): 3.5, ("MGC", 30): 18.2, ("MGC", 60): 26.2, ("MGC", 180): 47.8,
}
#: From CLAUDE_FUTURES.md §4 — commission plus estimated spread, round trip.
COST_BPS: Final[dict[str, float]] = {"MNQ": 0.48, "MGC": 0.65}

CRYPTO_ALPHA: Final[dict[int, float]] = {50: 0.0312, 100: 0.0359, 250: 0.0400, 500: 0.0500}
CRYPTO_COVERAGE: Final[dict[int, float]] = {50: 92.95, 100: 93.40, 250: 94.05, 500: 94.75}
CRYPTO_FLOOR: Final[float] = 0.1592
CRYPTO_EXPONENT: Final[float] = -0.321

ALPHA_GRID: Final[np.ndarray] = np.array(
    [0.010, 0.015, 0.020, 0.025, 0.030, 0.035, 0.040, 0.045, 0.050, 0.060, 0.070]
)
TARGET: Final[float] = 0.95


def pooled_alpha(rows: list[dict]) -> dict[int, dict]:
    """Pool the coverage curves across all six series at each block count.

    NO SINGLE CELL RESOLVES THE MAPPING. At 2,000 replications the Monte Carlo error on a
    coverage near 95% is +/-0.96 points, and the spread between cells at a given block count
    is 0.8-1.5 points — the same size. Pooling the six (product, horizon) series gives
    12,000 replications per block count and +/-0.39 points, which is what makes the curve
    interpretable at all. The per-cell numbers are still reported, as evidence that they do
    not separate.
    """
    out: dict[int, dict] = {}
    for nb in sorted({r["n_blocks"] for r in rows}):
        cells = [r for r in rows if r["n_blocks"] == nb and r.get("coverage")]
        if not cells:
            continue
        curves = np.array([r["coverage"] for r in cells])
        mean = curves.mean(axis=0)
        reps = sum(r["reps"] for r in cells)
        star = None
        if mean[0] >= TARGET:
            for i in range(1, mean.size):
                if mean[i] < TARGET <= mean[i - 1]:
                    span = mean[i - 1] - mean[i]
                    w = (mean[i - 1] - TARGET) / span if span > 0 else 0.0
                    star = float(ALPHA_GRID[i - 1] + w * (ALPHA_GRID[i] - ALPHA_GRID[i - 1]))
                    break
            else:
                star = float(ALPHA_GRID[-1])
        idx05 = int(np.argmin(np.abs(ALPHA_GRID - 0.05)))
        out[nb] = {
            "coverage_at_05": float(mean[idx05]) * 100,
            "alpha_star": star,
            "reps": reps,
            "se": 1.96 * float(np.sqrt(0.95 * 0.05 / reps)) * 100,
            "per_cell": [(r["product"], r["horizon"], r["coverage_at_05"] * 100
                          if r["coverage_at_05"] < 1.5 else r["coverage_at_05"])
                         for r in cells],
        }
    return out


def render(alpha_rows: list[dict], floor_cells: list[dict]) -> str:
    w: list[str] = []
    a = w.append
    a("# Stage 1 calibration — re-measured on futures")
    a("")
    a("Generated by `python -m futuresres.reporting.calibration_report`. "
      "CLAUDE_FUTURES.md §4, §5 Stage 1, §7.")
    a("")
    a("Both numbers the pipeline used were measured on Bitcoin. §4 flags them as inherited "
      "and wrong until re-measured; this is that measurement, and it **unblocks Stage 1**.")
    a("")

    # ── A ──────────────────────────────────────────────────────────────────
    pooled = pooled_alpha(alpha_rows)
    a("## A. The bootstrap α")
    a("")
    a("Coverage of the percentile interval on the signed shift `evaluate_signed_signal` "
      "computes, block-bootstrapped with the same 240-bar blocks, on **contiguous windows "
      "of real returns** — so the tail and the serial dependence are the market's own, not "
      "a model's. Under the null the signal is independent of returns, so the true shift is "
      "zero and coverage is the fraction of intervals containing it.")
    a("")
    a("| blocks | futures coverage at α=0.05 | ± | crypto | **futures α\\*** | crypto α\\* |")
    a("|---|---|---|---|---|---|")
    for nb, p in sorted(pooled.items()):
        star = f"**{p['alpha_star']:.4f}**" if p["alpha_star"] else "**unreachable**"
        ck = CRYPTO_COVERAGE.get(nb)
        ca = CRYPTO_ALPHA.get(nb)
        a(f"| {nb} | {p['coverage_at_05']:.2f}% | {p['se']:.2f} | "
          f"{f'{ck:.2f}%' if ck else '—'} | {star} | {ca if ca else '—'} |")
    a("")
    a(f"Pooled across all six (product, horizon) series — "
      f"{list(pooled.values())[0]['reps']:,} replications per block count.")
    a("")

    a("### The 115-vs-226 kurtosis gap does not show up in coverage")
    a("")
    a("This was the reason for measuring MNQ and MGC separately, and the answer is that "
      "they do not separate:")
    a("")
    a("| blocks | per-cell coverage range | spread | Monte Carlo error |")
    a("|---|---|---|---|")
    for nb in sorted(pooled):
        vals = [r["coverage_at_05"] * 100 for r in alpha_rows if r["n_blocks"] == nb]
        a(f"| {nb} | {min(vals):.2f}% – {max(vals):.2f}% | {max(vals) - min(vals):.2f} pts "
          f"| ±0.96 pts |")
    a("")
    a("**The spread between cells is the same size as the noise on each.** MNQ at γ₄ = 115 "
      "and MGC at γ₄ = 226 produce coverage that cannot be told apart at 2,000 "
      "replications, and neither can the 1m, 60m and 180m horizons. A single calibration is "
      "therefore what the data supports — six would be fitting noise.")
    a("")
    a("### What to use")
    a("")
    smallest = min(pooled)
    largest = max(pooled)
    a(f"Under-coverage is real but **milder than crypto's**: about "
      f"{95 - pooled[smallest]['coverage_at_05']:.1f} points short at {smallest} blocks, "
      f"narrowing to {95 - pooled[largest]['coverage_at_05']:.1f} at {largest}. Note it "
      f"**never reaches 95%**, so nominal 0.05 is not self-correcting at large samples the "
      f"way crypto's table implied — a small correction applies at every block count.")
    a("")

    # ── B ──────────────────────────────────────────────────────────────────
    a("## B. The detection floor")
    a("")
    a("Smallest injected effect promoted end-to-end at ≥80%, in units of one bar's "
      "volatility at the horizon swept. Noise is a contiguous window of real returns; the "
      "edge is a slow regime flipping every ~500 bars, the crypto construction.")
    a("")
    a("| product | horizon | independent obs in 16 years | best measured floor | at n |")
    a("|---|---|---|---|---|")
    for c in floor_cells:
        best = None
        for cur in c["curves"]:
            if cur.get("floor") and (best is None or cur["floor"] < best[0]):
                best = (cur["floor"], cur["n"])
        # Split out rather than inlined: as one expression the trailing ternary binds to
        # the whole concatenation, so a cell with no floor would emit " — |" as the ENTIRE
        # row instead of just its last two fields.
        floor_cell = f"**{best[0]:.4g}×**" if best else "**never resolved**"
        at_cell = f"{best[1]:,}" if best else "—"
        a(f"| {c['product']} | {c['horizon']}m | {c['available']:,} | {floor_cell} "
          f"| {at_cell} |")
    a("")

    a("### Scaling: crypto's −0.321 is not reproduced")
    a("")
    a("| product | horizon | exponent | points | vs √n (−0.5) |")
    a("|---|---|---|---|---|")
    for c in floor_cells:
        fit = c["fit"]
        e = fit.get("exponent")
        pts = fit.get("n_points", 0)
        if e is None:
            a(f"| {c['product']} | {c['horizon']}m | — | {pts} | not enough floors |")
        else:
            if abs(e) < 1e-9:
                verdict = "**degenerate** — both rungs gave the same floor"
            elif e < -0.65:
                verdict = "steeper"
            elif abs(e + 0.5) < 0.15:
                verdict = "matches"
            else:
                verdict = "shallower"
            a(f"| {c['product']} | {c['horizon']}m | **{e:+.3f}** | {pts} | {verdict} |")
    a("")
    a(f"Crypto measured **{CRYPTO_EXPONENT:+.3f}** — markedly shallower than √n, meaning "
      f"more data bought less than expected. **Futures run −0.61 to −0.69**, and the three "
      f"real fits agree closely: both 1-minute cells land on exactly −0.686 (each from the "
      f"same 0.3 → 0.1592 → 0.04481 ladder over 5k/20k/80k) and MGC 60m on −0.613. That is "
      f"**at or steeper than √n**, so more data helps more here than it did there.")
    a("")
    a("Caveats, in order of size. MGC 180m's +0.000 is not a measurement — both resolving "
      "rungs returned the same 0.3× because that is the top of the grid, so there is no "
      "slope to fit and it should be read as \"no estimate\", not as \"flat\". MNQ 60m and "
      "180m produced only ONE floor each, so no fit is possible at all. And every floor "
      "sits on a rung of a 1.885× ladder, carrying roughly half a rung of resolution — "
      "which is wide enough that −0.61 and −0.69 are not meaningfully different from each "
      "other.")
    a("")
    a("So the honest summary is: **three independent fits, all between −0.6 and −0.7, none "
      "consistent with crypto's −0.321.** The direction is settled even though the third "
      "decimal is not.")
    a("")
    # ── the translation that matters ───────────────────────────────────────
    a("## C. What this means: the constraint has inverted")
    a("")
    a("The crypto catalog closed because effects were **detectable but too small to trade** "
      "— everything measured sat under an 8 bps commission floor. Converting these floors "
      "to basis points against §4's cost floor asks whether that is still the binding "
      "constraint.")
    a("")
    a("| product | horizon | σ per bar | best floor | **floor in bps** | cost floor | ratio |")
    a("|---|---|---|---|---|---|---|")
    for c in floor_cells:
        best = None
        for cur in c["curves"]:
            if cur.get("floor") and (best is None or cur["floor"] < best[0]):
                best = (cur["floor"], cur["n"])
        sigma = SIGMA_BPS.get((c["product"], c["horizon"]))
        cost = COST_BPS[c["product"]]
        if best is None or sigma is None:
            a(f"| {c['product']} | {c['horizon']}m | "
              + (f"{sigma:.1f} bps" if sigma else "—")
              + f" | never resolved | — | {cost} bps | — |")
            continue
        bps = best[0] * sigma
        a(f"| {c['product']} | {c['horizon']}m | {sigma:.1f} bps | {best[0]:.4g}× | "
          f"**{bps:.2f} bps** | {cost} bps | {bps / cost:.1f}× |")
    a("")
    a("**The constraint inverts WITH HORIZON, and both regimes are present here.**")
    a("")
    a("- **At one minute the floors sit BELOW the cost floor** — 0.17 bps against MNQ's "
      "0.48, 0.16 against MGC's 0.65. This is the crypto situation exactly: the pipeline "
      "can establish effects far too small to trade, so COST binds and detection is the "
      "easy part.")
    a("- **At 60 and 180 minutes the floors sit 5x to 33x ABOVE it** — 2.57 to 15.66 bps "
      "on MNQ, 4.17 to 14.34 on MGC. Here the relationship reverses: anything the pipeline "
      "can see is comfortably tradeable, and anything too small to see would have paid "
      "handsomely. DETECTION binds.")
    a("")
    a("Aggregation is what flips it. Moving from 1m to 180m multiplies the bar's volatility "
      "by about 13x while dividing the sample by 180, and the floor responds to sample size "
      "far more than the cost does to anything. So the question a hypothesis must answer "
      "depends on where it operates: at one minute, *is the effect bigger than half a basis "
      "point*; at three hours, *is it bigger than fifteen*.")
    a("")
    a("**Most of this catalog operates at 30 minutes and longer**, which puts it in the "
      "detection-bound regime — the opposite of the regime that closed the crypto catalog, "
      "and the reason the per-hypothesis check in `reports/detectability.md` matters more "
      "than a cost screen would.")
    a("")
    a("### The hard limit at long horizons")
    a("")
    a("Aggregating to 60 or 180 minutes thins the tail — `reports/kurtosis.md` shows γ₄ "
      "falling from 115/226 at 1m to 19/14 at 180m — but it destroys sample size, and "
      "sample size is what the floor actually responds to:")
    a("")
    for c in floor_cells:
        if c["horizon"] == 1:
            continue
        resolved = [cur for cur in c["curves"] if cur.get("floor")]
        a(f"- **{c['product']} {c['horizon']}m**: {c['available']:,} independent "
          f"observations in sixteen years, so the largest testable sample is "
          f"{max(cur['n'] for cur in c['curves']):,} — "
          + (f"{len(resolved)} of {len(c['curves'])} rungs resolved a floor."
             if resolved else
             "**no rung resolved a floor at all.**"))
    a("")
    a("**MGC at 180 minutes has the highest floor measured anywhere: 0.3×, about 14 bps.** "
      "That is the top rung of the swept ladder — 0.1592× failed to reach 80% and 0.3× "
      "reached it — so the floor is bracketed in (0.1592, 0.3]. It is RESOLVED, not "
      "unresolved: it is simply high, for the reason the column above gives. 8,190 "
      "independent observations is the smallest sample in the study.")
    a("")
    a("The practical consequence is unchanged. A 180-minute MGC hypothesis must clear "
      "roughly 14 bps before the pipeline can see it at all, and a null below that carries "
      "no information — §7's rule applied to the number this sweep measured.")
    a("")
    return "\n".join(w)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="futuresres.reporting.calibration_report")
    ap.parse_args(argv)
    alpha_path = REPORTS / "calibration_cache.json"
    floor_path = REPORTS / "floor_cache.json"
    if not alpha_path.exists():
        print(f"FAILED: {alpha_path} missing — run --part alpha first", file=sys.stderr)
        return 1
    if not floor_path.exists():
        print(f"FAILED: {floor_path} missing — run --part floor first", file=sys.stderr)
        return 1
    alpha_rows = json.loads(alpha_path.read_text(encoding="utf-8"))
    floor_cells = json.loads(floor_path.read_text(encoding="utf-8"))
    REPORT.write_text(render(alpha_rows, floor_cells), encoding="utf-8")
    print(f"wrote {REPORT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
