"""Catalog status: every hypothesis, its route, its counts, what closed it.

    python -m futuresres.reporting.catalog_status

Everything here is derived at run time from `hypotheses.yaml`, the detectability gate, the
measured firing rates and the per-hypothesis cell files. Nothing is transcribed by hand,
because a status report that drifts from the artifacts it summarises is worse than none.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Final

import numpy as np
import yaml

from futuresres.reporting.detectability import (
    SCAN_POSITIONS,
    SCAN_POSITIONS_DISJOINT,
    assess,
    load_cells,
    sessions_and_bars,
)
from futuresres.stats.dsr import expected_max_sharpe
from futuresres.stats.trials import TrialLog

ROOT: Final[Path] = Path(__file__).resolve().parents[3]
REPORTS: Final[Path] = ROOT / "reports"
REGISTRY: Final[Path] = ROOT / "hypotheses.yaml"
REPORT: Final[Path] = REPORTS / "catalog_status.md"

TRIAL_LOG: Final[Path] = ROOT / "trials.jsonl"
MEASUREMENT_LOG: Final[Path] = ROOT / "measurements.jsonl"


def trial_counts() -> tuple[dict[str, int], list[float], dict[str, int], int, bool]:
    """N per hypothesis, trial Sharpes, provenance split, measurements, chain status.

    Read from the append-only log, which is now the single source of truth. It used not to
    be: N was reconstructed by counting rows in `reports/f*_cells.json` because no runner
    wrote to the log. That reconstruction could not detect a deleted trial and silently lost
    anything never persisted - which is how F03's 117 MGC cells went missing from N while
    its retirement quoted their aggregate.
    """
    log = TrialLog(TRIAL_LOG)
    counts: dict[str, int] = {}
    sharpes: list[float] = []
    provenance = {"native": 0, "reconstructed": 0}
    for trial in log.read_all():
        counts[trial.hypothesis_id] = counts.get(trial.hypothesis_id, 0) + 1
        if trial.sharpe is not None:
            sharpes.append(trial.sharpe)
        for kind in provenance:
            if f"provenance={kind}" in trial.note:
                provenance[kind] += 1
                break
    measurements = len(TrialLog(MEASUREMENT_LOG)) if MEASUREMENT_LOG.exists() else 0
    return counts, sharpes, provenance, measurements, log.verify_chain().ok


def render() -> str:
    registry = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    reg = {e["id"]: e for e in registry}
    cells = load_cells()
    session_counts = {p: sessions_and_bars(p)[0] for p in ("MNQ", "MGC")}
    verdicts: dict[str, list] = {}
    for entry in registry:
        if entry["status"] == "excluded":
            continue
        verdicts[entry["id"]] = assess(entry, cells, session_counts)

    counts, sharpes, provenance, n_measurements, chain_ok = trial_counts()
    n_trials = sum(counts.values())
    variance = float(np.var(sharpes, ddof=1)) if len(sharpes) > 1 else 0.0
    sr_star = expected_max_sharpe(n_trials, variance) if n_trials > 1 else 0.0

    w: list[str] = []
    a = w.append
    a("# Catalog status")
    a("")
    a("Generated by `python -m futuresres.reporting.catalog_status`. Derived at run time "
      "from `hypotheses.yaml`, the detectability gate, `reports/firing_rates.json` and the "
      "per-hypothesis cell files — nothing here is transcribed by hand.")
    a("")

    # ------------------------------------------------------------------ headline
    resolved = [e for e in registry if e["status"] not in ("untested",)]
    untested = [e for e in registry if e["status"] == "untested"]
    a("## Where the catalog stands")
    a("")
    schedulable = [e for e in untested if e.get("schedulable") is not False]
    blocked_spec = [e for e in untested if e.get("schedulable") is False]
    a(f"**{len(registry)} hypotheses registered. {len(schedulable)} schedulable. "
      f"0 promoted.**")
    a("")
    if blocked_spec:
        a(f"**{len(blocked_spec)} more are `untested` but NOT schedulable** — "
          + ", ".join(e["id"] for e in blocked_spec)
          + " carry open specification defects (undefined terms, or a trigger that fires on "
            "almost every arming). A vacuous condition with plenty of events produces a "
            "confident-looking result about nothing, and no event-count gate catches that. "
            "See `reports/decisions.md` §23 and §25.")
        a("")
    a("")
    a("| status | count | meaning |")
    a("|---|---|---|")
    order = ["untested", "retired", "stage1_uninformative",
             "blocked_insufficient_events", "excluded"]
    meaning = {
        "untested": "not yet run",
        "retired": "closed - by evidence, by premise, or by power; see decisions.md 33",
        "stage1_uninformative": "run, but no sample could carry a verdict",
        "blocked_insufficient_events": "never run — arithmetic closed every route first",
        "excluded": "not registered for testing",
    }
    for st in order:
        n = sum(1 for e in registry if e["status"] == st)
        if n:
            a(f"| `{st}` | {n} | {meaning[st]} |")
    a("")
    counts_pre, _, _, _, _ = trial_counts()
    closed = [e for e in registry
              if e["status"] in ("retired", "stage1_uninformative",
                                 "blocked_insufficient_events")]
    by_evidence = [e for e in closed
                   if e["status"] == "retired" and counts_pre.get(e["id"], 0) > 0]
    never_ran = [e for e in closed if counts_pre.get(e["id"], 0) == 0]
    def _join(ids: list[str]) -> str:
        if len(ids) <= 1:
            return "".join(ids)
        return ", ".join(ids[:-1]) + " and " + ids[-1]

    uninformative = [e["id"] for e in closed
                     if e["status"] == "stage1_uninformative"]
    a(f"**{len(closed) - len(by_evidence)} of the {len(closed)} closures were decided "
      f"without a result.** Only {_join([e['id'] for e in by_evidence])} were closed by "
      f"evidence. {_join([e['id'] for e in never_ran])} never ran at all — arithmetic or "
      f"premise closed them first — and {_join(uninformative)} ran but could not inform. "
      "That ratio is the honest summary of this catalog so far: the binding constraint has "
      "been event scarcity, registration defects and control design, not the absence of "
      "signal, and those are different findings that a results table would render "
      "identically.")
    a("")
    a("**Exactly one hypothesis has been tested to a standard where a null means the effect "
      "is ABSENT rather than undetectable: F05.** 45 informative cells on 11,000-18,600 "
      "events, best cell at 0.05x its detection floor. Every other closure turned on "
      "sample, premise or arithmetic. See `reports/decisions.md` §33 for the grading.")
    a("")

    # ------------------------------------------------------------------ N and SR*
    a("## Trial cost")
    a("")
    a("| | |")
    a("|---|---|")
    a(f"| **N (trials spent)** | **{n_trials}** |")
    a(f"| variance of trial Sharpes, V | {variance:.6f} |")
    a(f"| **expected max Sharpe under the null, SR\\*** | **{sr_star:.4f}** |")
    a(f"| natively logged | {provenance['native']} |")
    a(f"| reconstructed by backfill | {provenance['reconstructed']} |")
    a(f"| hash chain | {'**verified**' if chain_ok else '**BROKEN**'} |")
    a("")
    a("| hypothesis | trials |")
    a("|---|---|")
    for hid in sorted(counts):
        a(f"| {hid} | {counts[hid]} |")
    a("")
    a("SR\\* is the Sharpe the best of N random trials would be expected to reach by "
      f"chance. Any candidate must clear **{sr_star:.4f}** before its Sharpe means "
      "anything, and that bar rises with every trial spent - including the 72 spent on "
      "F07, which could not have produced evidence.")
    a("")
    a(f"**N now comes from `trials.jsonl`, whose chain verifies.** It used to be "
      f"reconstructed by counting rows in output files, which could not detect a deleted "
      f"trial and silently lost anything never persisted. All "
      f"{provenance['reconstructed']} records predating the wiring are marked "
      f"`reconstructed`: their timestamps are the backfill's, their within-run ordering is "
      f"whatever the output file held, and nothing proves those files were not edited "
      f"between the run and the backfill. They count toward N - a look at the data is a "
      f"look at the data - but they are not evidence that a log was being kept.")
    a("")
    a(f"**{n_measurements} firing-rate measurements are chained separately in "
      f"`measurements.jsonl` and are NOT in N.** They count how often a condition triggers "
      f"and compute no return series, so they could never produce a candidate. Including "
      f"them would raise SR\\* - a stricter bar, which sounds safe, but a bar set by a "
      f"category error is not conservative. See `reports/decisions.md` §16.")
    a("")

    # ------------------------------------------------------------------ per hypothesis
    a("## Every hypothesis")
    a("")
    a("`per-cell` is the count one Stage 1 cell sees; `aggregate` pools the scanned "
      "positions and is available only when they are disjoint in time. Both are compared "
      "against the smallest sample at which a detection floor ever resolved.")
    a("")
    a("| id | name | status | per-cell route | aggregate route | closed by | trials |")
    a("|---|---|---|---|---|---|---|")
    for entry in registry:
        hid = entry["id"]
        vs = verdicts.get(hid, [])
        pos = SCAN_POSITIONS.get(hid, 1)
        dj = SCAN_POSITIONS_DISJOINT.get(hid, True)
        if not vs:
            cell_route = agg_route = "—"
        else:
            openc = [v for v in vs if not v.blocked]
            if vs[0].status == "FIRING RATE UNMEASURED":
                cell_route = "rate unmeasured"
            elif openc:
                cell_route = f"**open** {len(openc)}/{len(vs)}"
            else:
                cell_route = "closed"
            if pos == 1:
                agg_route = "n/a"
            elif not dj:
                agg_route = "**closed** (overlap)"
            else:
                ok = [v for v in vs if v.aggregate_ceiling
                      and (c := cells.get((v.product, v.proxy_horizon)))
                      and c.ever_resolved
                      and min(v.aggregate_ceiling, v.data_ceiling)
                      >= (c.smallest_resolving_n or 0)]
                agg_route = f"**open** {len(ok)}/{len(vs)}" if ok else "closed"
        # EVERY status in the registry's closed set must appear here. Three were missing -
        # `stage1_inconclusive`, `stage1_passed` and `dead` - and this report crashed with a
        # KeyError the moment an entry carried one. It did, and the crash predates P03: a
        # reporting tool that dies on a legitimate status is a gap in the report, not a
        # reason to change the status. `.get` is deliberately NOT used: an unknown status
        # must fail loudly rather than render as a blank cell nobody notices.
        closed_by = {
            "retired": ("evidence" if counts.get(hid, 0) > 0
                        else "premise — never run"),
            "stage1_inconclusive": "power — ran, did not resolve",
            "stage1_passed": "not closed — signal gate cleared only",
            "stage1_uninformative": "sample — ran, could not inform",
            "blocked_insufficient_events": "arithmetic — never ran",
            "excluded": "registration",
            "dead": "structure — invalidated",
            "untested": "—",
        }[entry["status"]]
        a(f"| {hid} | {entry['name']} | `{entry['status']}` | {cell_route} | {agg_route} | "
          f"{closed_by} | {counts.get(hid, 0)} |")
    a("")

    # ------------------------------------------------------------------ counts detail
    a("## Counts against the swept range")
    a("")
    a("| id | product | horizon | per-cell | aggregate | needs | status |")
    a("|---|---|---|---|---|---|---|")
    for hid in sorted(verdicts):
        for v in sorted(verdicts[hid], key=lambda v: (v.product, v.horizon)):
            c = cells.get((v.product, v.proxy_horizon))
            need = c.smallest_resolving_n if c and c.ever_resolved else None
            agg = (min(v.aggregate_ceiling, v.data_ceiling)
                   if v.aggregate_ceiling else None)
            a(f"| {hid} | {v.product} | {v.horizon}m | {v.effective:,} | "
              + (f"{agg:,}" if agg else "—") + " | "
              + (f"{need:,}" if need else "—") + f" | {v.status} |")
    a("")

    # ------------------------------------------------------------------ what remains
    a("## What remains testable, and by which route")
    a("")
    strong: list[str] = []
    weak: list[str] = []
    for hid, vs in verdicts.items():
        if reg[hid]["status"] != "untested":
            continue
        for v in vs:
            if v.blocked:
                continue
            (strong if v.product == "MNQ" else weak).append(
                f"{hid} {v.product} {v.horizon}m")
    a("**Strong-form routes** — MNQ, 99.13% coverage, no standing caveat:")
    a("")
    for s in sorted(strong):
        a(f"- {s}")
    a("")
    a("**Weak-form routes** — MGC, 70.47% coverage. Forward-filling thins measured "
      "volatility and biases toward apparent significance, so a null here is weaker "
      "evidence than the same null on MNQ:")
    a("")
    for s in sorted(weak):
        a(f"- {s}")
    a("")
    a("Plus the disjoint **aggregate** routes on F02, F03 and F04, which pool scanned "
      "positions and are the only way a scan carries a verdict once its cells are "
      "individually underpowered.")
    a("")
    a("**Nothing in the catalog has been promoted, and no Stage 1 has been run since the "
      "gate was corrected.** F03's and F04's verdicts predate the correction and were "
      "re-checked against it: F03's 13 slots are genuinely disjoint and its aggregate "
      "refutation stands; F04's per-cell base narrowed to MGC 120m and its best-cell "
      "figure was withdrawn and replaced. Neither verdict reversed.")
    a("")
    return "\n".join(w)


def main(argv: list[str] | None = None) -> int:
    argparse.ArgumentParser(prog="futuresres.reporting.catalog_status").parse_args(argv)
    REPORT.write_text(render(), encoding="utf-8")
    print(f"wrote {REPORT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
