"""V01 — reopen displacement reversion. The firing-rate ceiling, BEFORE registration.

A MEASUREMENT: no trial spent, no forward return computed; one record per product to
`measurements.jsonl` with `--log`.

    python -m futuresres.reporting.v01_reopen_rate --product MGC
    python -m futuresres.reporting.v01_reopen_rate --product INDEX
    python -m futuresres.reporting.v01_reopen_rate --log

THE CEILING ARGUMENT, WHICH NEEDS NO THRESHOLD. V01 fires at most once per daily reopen. So the
number of valid daily reopens with a nonzero displacement is the LARGEST count any threshold could
leave. If that ceiling is below the detection floor, every threshold is blocked and no threshold has
to be chosen - which matters, because the only threshold on offer is the displacement range where
U01's fill curve showed the excess, and choosing a range from a curve is a search over thresholds.

WHICH OPENS. The mechanism is the first print "after the CME maintenance break", i.e. the daily
18:00 ET reopen after the 17:00-18:00 halt. The Sunday reopen follows the weekend close, not the
maintenance break, so it is outside the condition by the mechanism's own wording - not because U01's
weekly panel lacked the excess. Weekly counts are reported anyway, beside it, so the reader can see
the exclusion does not decide the verdict.

VALIDITY. U01's rules, unchanged (`u01_gap_fill.events`): same contract, normal break, first print
within 5 minutes of the reopen, prior session traded within 5 minutes of its scheduled close. A zero
displacement has no direction to fade and is not counted.

FLOORS. A reversion "when real depth arrives" runs on minutes, so the 60-minute proxy floor is the
mechanism's own scale (19,722 MNQ, 5,620 MGC); the 180-minute proxy (5,884, 2,862) is the most
generous floor that exists and is reported beside it. Post-2021 decides (STAGES.md S8).

DISPLACEMENT SCALE, reported so a later registration can state a threshold in bps or volatility
units: |gap| in bps, and |gap| over the trailing 20-session realised volatility (ex ante).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Final

import numpy as np
import polars as pl

from futuresres.reporting.u01_gap_fill import events

ROOT: Final[Path] = Path(__file__).resolve().parents[3]
RESULT_JSON: Final[Path] = ROOT / "reports" / "v01_reopen_rate.json"
REPORT_MD: Final[Path] = ROOT / "reports" / "v01_reopen_rate.md"
FLOORS: Final[dict[str, dict[int, int]]] = {
    "INDEX": {60: 19_722, 180: 5_884}, "MGC": {60: 5_620, 180: 2_862},
}


def run(product: str) -> dict:
    ev = events(product).filter(pl.col("valid") & (pl.col("gap") != 0))
    out = {"product": product, "floors": FLOORS[product]}
    for kind in ("daily", "weekly"):
        k = ev.filter(pl.col("kind") == kind)
        g = k["gap"].abs().to_numpy() * 1e4
        sig = k["sigma_exante"].to_numpy() * 1e4
        ok = np.isfinite(sig) & (sig > 0)
        yrs = k["year"].to_numpy()
        out[kind] = {
            "ceiling_events": int(k.height),
            "post_2021": int((yrs >= 2021).sum()),
            "gap_bps_p10_p50_p90": [float(v) for v in np.percentile(g, [10, 50, 90])],
            "gap_over_sigma_p10_p50_p90": [float(v) for v in np.percentile(g[ok] / sig[ok], [10, 50, 90])],
            "share_ge_5bps": float(np.mean(g >= 5)),
        }
    return out


def render(res: dict) -> str:
    w: list[str] = []
    a = w.append
    a("# V01 — reopen displacement: the firing-rate ceiling")
    a("")
    a("Generated by `python -m futuresres.reporting.v01_reopen_rate`. **A measurement: no trial "
      "spent and no forward return computed.** `decisions.md` §69.")
    a("")
    a("Every valid daily reopen with a nonzero displacement is counted — the largest count ANY "
      "threshold could leave. Weekly (Sunday) reopens are outside the condition by the mechanism's "
      "wording (they follow the weekend close, not the maintenance break) and are shown for "
      "comparison only.")
    a("")
    a("| product | reopens | ceiling (every one fires) | post-2021 | floor 60m | floor 180m | below both? |")
    a("|---|---|---|---|---|---|---|")
    for p, r in res.items():
        for kind in ("daily", "weekly"):
            x = r[kind]
            tag = "**condition**" if kind == "daily" else "comparison only"
            f60 = r["floors"].get("60", r["floors"].get(60))
            f180 = r["floors"].get("180", r["floors"].get(180))
            a(f"| {p} | {kind} ({tag}) | **{x['ceiling_events']:,}** | {x['post_2021']:,} | "
              f"{f60:,} | {f180:,} | {'yes' if x['ceiling_events'] < min(f60, f180) else 'NO'} |")
    a("")
    a("## Displacement scale (for stating any threshold in bps or volatility units)")
    a("")
    a("| product | reopens | \\|gap\\| bps p10 / p50 / p90 | \\|gap\\| / σ ex ante p10 / p50 / p90 | share ≥ 5 bps |")
    a("|---|---|---|---|---|")
    for p, r in res.items():
        for kind in ("daily", "weekly"):
            x = r[kind]
            b, s = x["gap_bps_p10_p50_p90"], x["gap_over_sigma_p10_p50_p90"]
            a(f"| {p} | {kind} | {b[0]:.2f} / {b[1]:.2f} / {b[2]:.2f} | {s[0]:.3f} / {s[1]:.3f} / "
              f"{s[2]:.3f} | {x['share_ge_5bps']:.1%} |")
    a("")
    return "\n".join(w)


def log_measurements(res: dict) -> None:
    from futuresres.stats.trials import Trial, TrialLog
    log = TrialLog(ROOT / "measurements.jsonl")
    for p, r in res.items():
        rec = log.append(Trial(
            trial_id=log.next_id("m"), hypothesis_id="V01", symbol=p,
            date_range=("2010-06-06", "2026-08-27"), status="completed",
            params={"kind": "firing_rate_ceiling",
                    "daily_ceiling": r["daily"]["ceiling_events"],
                    "daily_post_2021": r["daily"]["post_2021"],
                    "weekly_ceiling_comparison_only": r["weekly"]["ceiling_events"],
                    "floors": {str(k): v for k, v in r["floors"].items()}},
            note=("kind=measurement; NOT a trial and NOT counted in N. V01 firing-rate CEILING: "
                  "every valid daily reopen with a nonzero displacement, the largest count any "
                  "threshold could leave. No forward return computed. decisions.md 69."),
        ))
        print(f"logged {rec['trial_id']} ({p})")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="futuresres.reporting.v01_reopen_rate")
    ap.add_argument("--product", choices=["MGC", "INDEX"],
                    help="one product per process: each events() build peaks near 600 MB")
    ap.add_argument("--log", action="store_true")
    args = ap.parse_args(argv)
    res: dict = json.loads(RESULT_JSON.read_text()) if RESULT_JSON.exists() else {}
    if args.product:
        res[args.product] = json.loads(json.dumps(run(args.product)))
        RESULT_JSON.write_text(json.dumps(res, indent=1) + "\n")
    REPORT_MD.write_text(render(res))
    print(f"wrote {RESULT_JSON.name}, {REPORT_MD.name}")
    if args.log:
        log_measurements(res)
    return 0


if __name__ == "__main__":
    sys.exit(main())
